### ISSUE TITLE
[moved to MINI3] example for multiple "models" and passing data between them

### ISSUE THREAD

**Issue by panique** [panique/mini2#25]
taken from php-mvc

**Comment by tankerkiller125** [comment]
Mabey something very similar to the original php-login model handling system? I rather enjoyed that system and found it very easy to use (for most cases). If I get a chance this week I'll make a fork and start playing around with model loading.

**Comment by panique** [comment]
hey guys, this is now implemented in MINI3, please find and test it here :) https://github.com/panique/mini3
