### ISSUE TITLE
[moved to MINI3] Rebuild the model from one file to 1+ files

### ISSUE THREAD

**Issue by panique** [panique/mini2#37]
Currently the model is just one class in one file. Totally okay for the main purpose of this script. But this is for sure not cool when your model gets bigger. Possible idea:

1. Use autoloading and static methods for model calls, so you could use something like `UserModel::getUserById(17)` everywhere in your app.

2. Or, autoload different model-classes, so the current `$model->getAllSongs();` would get another level, like `$model->SongModel->getAllSongs();`

**Comment by foxoverflow** [comment]
I personally prefer the idea/method 2, I like the object oriented style.

**Comment by Lorenzbi** [comment]
Is there any progress on this? I also like the second version.

**Comment by panique** [comment]
@Lorenzbi He, no, no progress on this, but feel free to build this feature.

**Comment by explorewp** [comment]
About the method, statical method seems more preferred & popular. The interface is simple, and no need to  function () use ($obj) {$obj->method();}

**Comment by panique** [comment]
INFO: This feature will come with MINI3, built on top of slim3, with full namespaces and multiple models :)

**Comment by dezudas** [comment]
@panique hope to see mini3 soon :) 👍

**Comment by panique** [comment]
hey, please find this feature now in MINI3 :) https://github.com/panique/mini3
