### ISSUE TITLE
[moved to MINI3] Upgrading from Slim 2 to Slim 3

### ISSUE THREAD

**Issue by cxj** [panique/mini2#40]
Any intentions regarding upgrading Mini2 to Slim 3 compatibility when it's released?  :-)

**Comment by panique** [comment]
Hey there, no plans yet, but I think somebody will commit a version for Slim 3 soon !

**Comment by cxj** [comment]
Thank you for the reply!

**Comment by panique** [comment]
As this is interesting I'd like to reopen this issue and give some links :)

Feed about Slim3:
http://www.slimframework.com/2015/08/10/slim3-beta2.html

BETA 3 for download:
https://github.com/slimphp/Slim/releases

I think this will work when require'ing `"slim/slim": "3.0.0-beta2"` in *composer.json*.

Cheers,
Chris

**Comment by panique** [comment]
Let's do this when there's a very stable Slim 3 release, usually some weeks after first 3.0 release...

**Comment by cxj** [comment]
Sounds like a sane plan to me.  ;-)

**Comment by panique** [comment]
By the way, it might take some months until Slim 3 is more popular than Slim 2, so it might be better to wait a long time until this framework really NEEDS Slim 3 under the hood. :)
