### ISSUE TITLE
MINI2 license

### ISSUE THREAD

**Issue by JulianLaval** [panique/mini2#42]
Hi!

Although it seems fairly obvious that MINI2 is completely open-source, I'm wondering if it'd be possible to explicitly give the project a license in the `README` or via a license file (e.g. MIT, GPL, Apache, etc)? Doing so would be immensely useful when it comes to using MINI2 in projects that require all licenses to be explicitly stated.

Cheers!

**Comment by panique** [comment]
Good point :) Does anybody has an idea what would be the best licence currently ? I have no real idea to be honest

**Comment by JulianLaval** [comment]
Thanks for your prompt reply :)

I see you've set [Huge](https://github.com/panique/huge#license) to MIT which makes sense if you're not really fussed about anything in particular - otherwise GPL might make sense if you want derivative works available under the same terms.

Definitely check out http://choosealicense.com/ if you're not sure!

**Comment by panique** [comment]
Thanks, MIT license has been added! :)
https://github.com/panique/mini2/blob/master/LICENSE
